import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('ar');
  Locale get locale => _locale;

  static const String _prefKey = 'selected_language';

  LanguageProvider() {
    _loadSavedLanguage();
  }

  void _loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final String? languageCode = prefs.getString(_prefKey);
    if (languageCode != null) {
      _locale = Locale(languageCode);
      notifyListeners();
    }
  }

  void setLanguage(String languageCode) async {
    if (_locale.languageCode == languageCode) return;

    _locale = Locale(languageCode);
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, languageCode);
  }

  bool get isArabic => _locale.languageCode == 'ar';

  String translate(String key) {
    final cleanKey = key.toLowerCase().trim();
    if (isArabic) {
      return _arabicStrings[cleanKey] ?? key;
    } else {
      return _englishStrings[cleanKey] ?? key;
    }
  }

  static const Map<String, String> _englishStrings = {
    // Categories from DB (Arabic Keys -> English Values)
    'مؤتمر': 'Conference',
    'ندوة': 'Seminar',
    'ورشة عمل': 'Workshop',
    'دورة تدريبية': 'Training Course',
    'ترفيه': 'Entertainment',
    'ملتقى علمي': 'Scientific Forum',
    'رياضة': 'Sports',
    'تقنية': 'Technical',
    'اجتماعية': 'Social',
    'معرض': 'Exhibition',

    'settings': 'Settings',
    'account': 'Account',
    'notifications': 'Notifications',
    'app_preferences': 'App Preferences',
    'support': 'Support',
    'about': 'About',
    'language': 'Language',
    'change_email': 'Change Email',
    'change_password': 'Change Password',
    'push_notifications': 'Push Notifications',
    'help_center': 'Help Center',
    'contact_support': 'Contact Support',
    'version': 'Version',
    'legal_notices': 'Legal Notices',
    'logout': 'Log Out',
    'select_language': 'Select Language',
    'english': 'English',
    'arabic': 'Arabic (العربية)',
    'cancel': 'Cancel',
    'confirm_logout': 'Are you sure you want to logout?',
    'home': 'Home',
    'my_tickets': 'My Tickets',
    'profile': 'Profile',
    'search': 'Search',
    'filters': 'Filters',
    'upcoming_events': 'Upcoming Events',
    'history': 'History',
    'retry': 'Retry',
    'connection_error': 'Connection Error',
    'update': 'Update',
    'change': 'Change',
    'current_email': 'Current Email',
    'new_email': 'New Email',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'verify_identity': 'Verify your identity to continue',
    'edit_profile': 'Edit Profile',
    'verified': 'Verified',
    'statistics': 'Statistics',
    'tickets_booked': 'Tickets Booked',
    'events_attended': 'Events Attended',
    'interests': 'Interests',
    'no_interests': 'No interests added yet.',
    'edit': 'Edit',
    'ended': 'Ended',
    'open_in_maps': 'Open in Maps',
    'forgot_password_title': 'Forgot Password',
    'forgot_password_msg': 'Enter your email address to receive a password reset code.',
    'email_label': 'EMAIL ADDRESS',
    'send_reset_code': 'Send Reset Code',
    'enter_email_error': 'Please enter your email address',
    'join_eventhub': 'Join EventHub',
    'create_premium_account': 'Create your premium account',
    'already_have_account_msg': 'Already have an account?',
    'full_name_label': 'Full Name',
    'password_label': 'Password',
    'confirm_password_label': 'Confirm Password',
    'create_account_btn': 'Create Account',
    'user_role': 'User',
    'assistant_role': 'Assistant',
    'verify_code_title': 'Verify Code',
    'verify_code_msg': 'We sent a 6-digit code to',
    'verification_code_label': 'VERIFICATION CODE',
    'reset_password_title': 'Reset Password',
    'reset_password_msg': 'Enter your new password below',
    'new_password_label': 'New Password',
    'reset_password_btn': 'Reset Password',
    'password_reset_success': 'Password reset successfully! Please login.',
    'passwords_dont_match': 'Passwords do not match',
    'password_min_length': 'Password must be at least 8 characters',
    'live_events': 'Live Events',
    'live': 'LIVE',
    'selling_fast': 'Selling Fast',
    'booking_closed': 'Booking Closed',
    'view_details': 'View Details',
    'view_tickets': 'View Tickets',
    'no_upcoming_events': 'No upcoming events',
    'no_live_events': 'No live events',
    'venue': 'Venue',
    'date': 'Date',
    'time': 'Time',
    'tickets': 'Tickets',
    'price': 'Price',
    'book_now': 'Book Now',
    'rate_review': 'Rate & Review',
    'rating': 'Rating',
    'reviews': 'Reviews',
    'description': 'Description',
    'organizer': 'Organizer',
    'all': 'All',
    'technical': 'Technical',
    'workshop': 'Workshop',
    'conference': 'Conference',
    'seminar': 'Seminar',
    'cultural': 'Cultural',
    'business': 'Business',
    'ai': 'AI',
    'networking': 'Networking',
    'fintech': 'FinTech',
    'innovation': 'Innovation',
    'sustainability': 'Sustainability',
    'entrepreneurship': 'Entrepreneurship',
    'other': 'Other',
    'confirmed': 'Confirmed',
    'used': 'Used',
    'pending': 'Pending',
    'valid': 'Valid',
    'my_events': 'My Events',
    'no_notifications': 'No notifications yet',
    'mark_all_read': 'Mark all as read',
    'apply_filters': 'Apply Filters',
    'categories': 'Categories',
    'started': 'Started',
    'open_for_booking': 'Open for Booking',
    'date_time': 'Date & Time',
    'organized_by': 'Organized by',
    'about_event': 'About This Event',
    'event_agenda': 'Event Agenda',
    'event_sponsors': 'Event Sponsors',
    'leave_review': 'Leave a Review',
    'see_all': 'See All',
    'confirm_booking': 'Confirm Booking',
    'booking_confirm_msg': 'Are you sure you want to book a ticket for',
    'ticket_booked_success': 'Ticket Booked Successfully!',
    'rating_submitted': 'Rating submitted!',
    'write_review': 'Write a review (optional)...',
    'submit_rating': 'Submit Rating',
    'capacity_bookings': 'Capacity & Bookings',
    'sold_out': 'Sold Out!',
    'booked': 'Booked',
    'no_history': 'No history yet',
    'book_ticket_hint': 'Book a ticket from Explore tab',
    'attended': 'Attended',
    'active': 'Active',
    'expired': 'Expired',
    'confirm': 'Confirm',
    'booking_closed_msg': 'Booking Closed',
    'already_booked': 'Already Booked',
    'notification_hint': "You'll get alerts for events, tickets & more",
    'agenda': 'Agenda Item',
    'access_ticket': 'Access Ticket',
    'scan_entrance': 'Scan at the entrance',
    'ticket_used': 'TICKET USED',
    'valid_ticket': 'VALID TICKET',
    'qr_safe_msg': 'Keep this QR code safe. You will need it to enter the event.',
    'ticket_label': 'TICKET',
    'passwords_not_match': 'Passwords do not match',
    'password_updated': 'Password updated successfully!',
    'email_updated': 'Email updated successfully!',
    'select_interests': 'Select Interests',
    'done': 'Done',
    'full_name': 'Full Name',
    'your_full_name': 'Your full name',
    'email_address': 'Email Address',
    'email_hint': 'you@example.com',
    'new_password_optional': 'New Password (optional)',
    'pass_hint': 'Leave empty to keep current',
    'profile_updated': 'Profile updated successfully!',
    'rate_event': 'Rate Event',
    'select_star_rating': 'Please select a star rating first.',
    'rating_success': 'Rating submitted successfully!',
    'based_on': 'Based on',
    'no_reviews_msg': 'No reviews yet for this event.',
    'rating_locked_msg': 'You must attend and scan your ticket to leave a review.',
    'share_event': 'Share Event',
    'share_msg': 'Check out this event on EventHub!',
    'sign_in': 'Sign In',
    'email': 'Email',
    'password': 'Password',
    'login': 'Login',
    'dont_have_account': "Don't have an account? ",
    'create_account': 'Create Account',
    'please_fill_all_fields': 'Please fill all fields',
    'premium_experiences': 'Premium Event Experiences',

    // Assistant Module
    'history_subtitle': "Past events you've assisted in",
    'search_event_name_hint': "Search by event name...",
    'no_past_events': "No Past Events",
    'completed_events_msg': "Completed events will appear here",
    'tba': "TBA",
    'untitled': "Untitled",
    'reject_invitation': "Reject Invitation",
    'reject_invitation_msg': "Are you sure you want to reject this invitation?",
    'reject': "Reject",
    'accept': "Accept",
    'invitation_accepted': "Invitation accepted! \u{1F389}",
    'invitation_rejected': "Invitation rejected",
    'assistant': "Assistant",
    'assistance_requests': "Assistance Requests",
    'no_pending_requests': "No Pending Requests",
    'new_invitations_msg': "New invitations will appear here",
    'untitled_event': "Untitled Event",
    'from': "From:",
    'my_work': "Task Board",
    'my_work_subtitle': "Events you're assigned to assist",
    'no_active_events': "No Active Events",
    'accept_invitations_msg': "Accept invitations to see events here",
    'available_for_assistance': "Available for Assistance",
    'available_desc': "Managers can find and invite you",
    'unavailable_desc': "You won't receive new invitations",
    'events_assisted': "Events Assisted",
    'tickets_scanned': "Tickets Scanned",
    'available_for_assistance_upper': "AVAILABLE FOR ASSISTANCE",
    'manager_label': "Manager:",
    'scanned': "Scanned",
    'upcoming_upper': "UPCOMING",
    'cannot_scan_msg': "Cannot scan: This event is currently",
    'scanning_allowed_msg': "Scanning is allowed only for Live events.",
    'scan_qr_code': "Scan QR Code",
    'scanning_locked': "Scanning Locked",
    'tap_to_open_camera': "Tap to open camera",
    'scanning_starts_when_live': "Scanning starts when event is Live",
    'total': "Total",
    'my_scans': "My Scans",
    'search_name_qr': "Search by name or QR code...",
    'registered_attendees': "Registered Attendees",
    'found': "found",
    'no_participants_found': "No participants found",
    'code_label': "Code:",
    'point_camera_ticket': "Point camera at ticket QR code",
    'processing': "Processing...",
    'checkin_successful': "Check-in Successful!",
    'checkin_failed': "Check-in Failed",
    'scan_next': "Scan Next",
    'entry_allowed': "Entry Allowed \u{2705}",
    'already_entered': "Already Entered \u{26A0}\u{FE0F}",
    'invalid_ticket': "Invalid Ticket \u{274C}",
    'not_your_event': "Not Your Event \u{1F6AB}",
    'error': "Error",
    'scanner': "Scanner",
    'participants': "Participants",
    'not_assigned_event': "You are not assigned to any event.",
    'event_participants': "Event Participants",
    'my_stats': "Your Statistics",
    'total_booked': "Total Booked",
    'total_scanned': "Total Scanned",
    'tickets_i_scanned': "Tickets I Scanned",
    'no_scans_recorded': 'No scans recorded',
    'completed_upper': 'COMPLETED',
    'date_time_label': 'Date & Time',
    'venue_label': 'Venue',
    'at': 'at',
    'jan': 'Jan', 'feb': 'Feb', 'mar': 'Mar', 'apr': 'Apr', 'may': 'May', 'jun': 'Jun',
    'jul': 'Jul', 'aug': 'Aug', 'sep': 'Sep', 'oct': 'Oct', 'nov': 'Nov', 'dec': 'Dec',
    'participating_companies': 'Participating Companies',
    'booth': 'Booth',
    'apply_for_exhibition': 'Apply for Exhibition',
    'exhibition_registration_closed': 'Registration Closed',
    'deadline_passed_msg': 'Deadline passed (closed 30 days before start)',
    'unlimited': 'Unlimited',
    'unlimited_ar': 'مفتوح',
  };

  static const Map<String, String> _arabicStrings = {
    // Categories from DB (Arabic Keys -> Arabic Values)
    'مؤتمر': 'مؤتمر',
    'ندوة': 'ندوة',
    'ورشة عمل': 'ورشة عمل',
    'دورة تدريبية': 'دورة تدريبية',
    'ترفيه': 'ترفيه',
    'ملتقى علمي': 'ملتقى علمي',
    'رياضة': 'رياضة',
    'تقنية': 'تقنية',
    'اجتماعية': 'اجتماعية',
    'معرض': 'معرض',

    'settings': 'الإعدادات',
    'account': 'الحساب',
    'notifications': 'الإشعارات',
    'app_preferences': 'تفضيلات التطبيق',
    'support': 'الدعم',
    'about': 'حول التطبيق',
    'language': 'اللغة',
    'change_email': 'تغيير البريد الإلكتروني',
    'change_password': 'تغيير كلمة المرور',
    'push_notifications': 'تنبيهات الهاتف',
    'help_center': 'مركز المساعدة',
    'contact_support': 'الاتصال بالدعم',
    'version': 'الإصدار',
    'legal_notices': 'ملاحظات قانونية',
    'logout': 'تسجيل الخروج',
    'select_language': 'اختر اللغة',
    'english': 'الإنجليزية (English)',
    'arabic': 'العربية',
    'cancel': 'إلغاء',
    'confirm_logout': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'home': 'الرئيسية',
    'my_tickets': 'تذاكري',
    'profile': 'الملف الشخصي',
    'search': 'بحث',
    'filters': 'تصفية',
    'upcoming_events': 'الفعاليات القادمة',
    'history': 'السجل',
    'retry': 'إعادة المحاولة',
    'connection_error': 'خطأ في الاتصال',
    'update': 'تحديث',
    'change': 'تغيير',
    'current_email': 'البريد الإلكتروني الحالي',
    'new_email': 'البريد الإلكتروني الجديد',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'verify_identity': 'يرجى تأكيد هويتك للمتابعة',
    'edit_profile': 'تعديل الملف الشخصي',
    'verified': 'موثق',
    'statistics': 'الإحصائيات',
    'tickets_booked': 'التذاكر المحجوزة',
    'events_attended': 'الفعاليات التي حضرتها',
    'interests': 'الاهتمامات',
    'no_interests': 'لا توجد اهتمامات مضافة بعد.',
    'edit': 'تعديل',
    'live_events': 'فعاليات مباشرة',
    'live': 'مباشر',
    'selling_fast': 'تنفد بسرعة',
    'booking_closed': 'الحجز مغلق',
    'view_details': 'عرض التفاصيل',
    'view_tickets': 'عرض التذاكر',
    'no_upcoming_events': 'لا توجد فعاليات قادمة',
    'no_live_events': 'لا توجد فعاليات مباشرة حالياً',
    'venue': 'القاعة',
    'date': 'التاريخ',
    'time': 'الوقت',
    'tickets': 'التذاكر',
    'price': 'السعر',
    'book_now': 'احجز الآن',
    'rate_review': 'التقييم والمراجعة',
    'rating': 'التقييم',
    'reviews': 'المراجعات',
    'description': 'الوصف',
    'organizer': 'المنظم',
    'all': 'الكل',
    'technical': 'تقني',
    'workshop': 'ورشة عمل',
    'conference': 'مؤتمر',
    'seminar': 'ندوة',
    'cultural': 'ثقافي',
    'business': 'الأعمال',
    'ai': 'الذكاء الاصطناعي',
    'networking': 'التواصل',
    'fintech': 'التقنية المالية',
    'innovation': 'الابتكار',
    'sustainability': 'الاستدامة',
    'entrepreneurship': 'ريادة الأعمال',
    'other': 'أخرى',
    'confirmed': 'مؤكد',
    'used': 'مستخدم',
    'pending': 'قيد الانتظار',
    'valid': 'صالح',
    'my_events': 'فعالياتي',
    'no_notifications': 'لا توجد إشعارات بعد',
    'mark_all_read': 'تحديد الكل كمقروء',
    'apply_filters': 'تطبيق الفلتر',
    'categories': 'التصنيفات',
    'started': 'بدأت',
    'open_for_booking': 'مفتوح للحجز',
    'date_time': 'التاريخ والوقت',
    'organized_by': 'بواسطة',
    'about_event': 'حول الفعالية',
    'event_agenda': 'جدول الفعالية',
    'event_sponsors': 'رعاة الفعالية',
    'leave_review': 'أضف مراجعة',
    'see_all': 'مشاهدة الكل',
    'confirm_booking': 'تأكيد الحجز',
    'booking_confirm_msg': 'هل أنت متأكد أنك تريد حجز تذكرة لـ',
    'ticket_booked_success': 'تم حجز التذكرة بنجاح!',
    'rating_submitted': 'تم إرسال التقييم!',
    'write_review': 'اكتب مراجعة (اختياري)...',
    'submit_rating': 'إرسال التقييم',
    'capacity_bookings': 'السعة والحجوزات',
    'sold_out': 'نفدت التذاكر!',
    'booked': 'محجوز',
    'no_history': 'لا يوجد سجل بعد',
    'book_ticket_hint': 'احجز تذكرة من قسم الاستكشاف',
    'attended': 'حضر',
    'active': 'نشط',
    'ended': 'انتهى',
    'open_in_maps': 'فتح في الخرائط',
    'forgot_password_title': 'نسيت كلمة المرور',
    'forgot_password_msg': 'أدخل عنوان بريدك الإلكتروني لتلقي رمز إعادة تعيين كلمة المرور.',
    'email_label': 'البريد الإلكتروني',
    'send_reset_code': 'إرسال رمز إعادة التعيين',
    'enter_email_error': 'يرجى إدخال عنوان بريدك الإلكتروني',
    'join_eventhub': 'انضم إلى EventHub',
    'create_premium_account': 'أنشئ حسابك المتميز',
    'already_have_account_msg': 'هل لديك حساب بالفعل؟',
    'full_name_label': 'الاسم الكامل',
    'password_label': 'كلمة المرور',
    'confirm_password_label': 'تأكيد كلمة المرور',
    'user_role': 'مستخدم',
    'assistant_role': 'مساعد',
    'create_account_btn': 'إنشاء حساب',
    'verify_code_title': 'تحقق من الرمز',
    'verify_code_msg': 'لقد أرسلنا رمزًا مكونًا من 6 أرقام إلى',
    'verification_code_label': 'رمز التحقق',
    'reset_password_title': 'إعادة تعيين كلمة المرور',
    'reset_password_msg': 'أدخل كلمة المرور الجديدة أدناه',
    'new_password_label': 'كلمة المرور الجديدة',
    'reset_password_btn': 'إعادة تعيين كلمة المرور',
    'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح! يرجى تسجيل الدخول.',
    'passwords_dont_match': 'كلمات المرور غير متطابقة',
    'password_min_length': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'confirm': 'تأكيد',
    'booking_closed_msg': 'الحجز مغلق',
    'already_booked': 'تم الحجز مسبقاً',
    'notification_hint': 'ستصلك تنبيهات حول الفعاليات والتذاكر والمزيد',
    'agenda': 'فقرة في الجدول',
    'access_ticket': 'الدخول للتذكرة',
    'scan_entrance': 'امسح الرمز عند المدخل',
    'ticket_used': 'تذكرة مستخدمة',
    'valid_ticket': 'تذكرة صالحة',
    'qr_safe_msg': 'حافظ على هذا الرمز آمناً. ستحتاج إليه لدخول الفعالية.',
    'ticket_label': 'تذكرة',
    'passwords_not_match': 'كلمات المرور غير متطابقة',
    'password_updated': 'تم تحديث كلمة المرور بنجاح!',
    'email_updated': 'تم تحديث البريد الإلكتروني بنجاح!',
    'select_interests': 'اختر اهتماماتك',
    'done': 'تم',
    'full_name': 'الاسم بالكامل',
    'your_full_name': 'اسمك بالكامل',
    'email_address': 'البريد الإلكتروني',
    'email_hint': 'you@example.com',
    'new_password_optional': 'كلمة مرور جديدة (اختياري)',
    'pass_hint': 'اتركه فارغاً للاحتفاظ بالحالية',
    'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
    'rate_event': 'تقييم الفعالية',
    'select_star_rating': 'يرجى اختيار عدد النجوم أولاً.',
    'rating_success': 'تم إرسال التقييم والمراجعة بنجاح!',
    'based_on': 'بناءً على',
    'no_reviews_msg': 'لا توجد مراجعات لهذه الفعالية بعد.',
    'rating_locked_msg': 'يجب حضور الفعالية ومسح التذكرة لتتمكن من التقييم والتعليق.',
    'share_event': 'مشاركة الفعالية',
    'share_msg': 'شاهد هذه الفعالية على EventHub!',
    'sign_in': 'تسجيل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'login': 'دخول',
    'dont_have_account': 'ليس لديك حساب؟ ',
    'create_account': 'إنشاء حساب',
    'please_fill_all_fields': 'الرجاء تعبئة جميع الحقول',
    'premium_experiences': 'تجارب فعاليات استثنائية',

    // Assistant Module
    'history_subtitle': "الفعاليات التي ساعدت بها",
    'search_event_name_hint': "البحث باسم الحدث...",
    'no_past_events': "لا توجد فعاليات سابقة",
    'completed_events_msg': "الفعاليات المكتملة ستظهر هنا",
    'tba': "يحدد لاحقاً",
    'untitled': "بدون عنوان",
    'reject_invitation': "رفض الدعوة",
    'reject_invitation_msg': "هل أنت متأكد من رفض هذه الدعوة؟",
    'reject': "رفض",
    'accept': "قبول",
    'invitation_accepted': "تم قبول الدعوة! \u{1F389}",
    'invitation_rejected': "تم رفض الدعوة",
    'assistant': "مساعد",
    'assistance_requests': "طلبات المساعدة",
    'no_pending_requests': "لا توجد طلبات معلقة",
    'new_invitations_msg': "الدعوات الجديدة ستظهر هنا",
    'untitled_event': "فعالية بدون عنوان",
    'from': "من:",
    'my_work': "لوحة المهام",
    'my_work_subtitle': "الفعاليات المعين لمساعدتها",
    'no_active_events': "لا توجد فعاليات نشطة",
    'accept_invitations_msg': "اقبل الدعوات لرؤية الفعاليات هنا",
    'available_for_assistance': "متاح للمساعدة",
    'available_desc': "يمكن للمنظمين العثور عليك ودعوتك",
    'unavailable_desc': "لن تتلقى دعوات جديدة",
    'events_assisted': "الفعاليات التي شاركت بها",
    'tickets_scanned': "التذاكر الممسوحة",
    'available_for_assistance_upper': "متاح للمساعدة",
    'manager_label': "المدير:",
    'scanned': "تم المسح",
    'upcoming_upper': "قادم",
    'cannot_scan_msg': "لا يمكن المسح: هذه الفعالية حالياً",
    'scanning_allowed_msg': "المسح متاح فقط للفعاليات المباشرة.",
    'scan_qr_code': "مسح رمز الاستجابة",
    'scanning_locked': "المسح مقفل",
    'tap_to_open_camera': "انقر لفتح الكاميرا",
    'scanning_starts_when_live': "يبدأ المسح عندما تكون الفعالية مباشرة",
    'total': "الإجمالي",
    'my_scans': "مسحاتي",
    'search_name_qr': "ابحث بالاسم أو برمز التذكرة...",
    'registered_attendees': "الحضور المسجلون",
    'found': "موجود",
    'no_participants_found': "لم يتم العثور على أي مشاركين",
    'code_label': "الرمز:",
    'point_camera_ticket': "وجه الكاميرا نحو رمز الاستجابة للتذكرة",
    'processing': "جاري المعالجة...",
    'checkin_successful': "تم تسجيل الدخول بنجاح!",
    'checkin_failed': "فشل تسجيل الدخول",
    'scan_next': "مسح التالي",
    'entry_allowed': "مسموح بالدخول \u{2705}",
    'already_entered': "دخل مسبقاً \u{26A0}\u{FE0F}",
    'invalid_ticket': "تذكرة غير صالحة \u{274C}",
    'not_your_event': "ليست فعاليتك \u{1F6AB}",
    'error': "خطأ",
    'scanner': "الماسح الضوئي",
    'participants': "المشاركون",
    'not_assigned_event': "أنت غير معين لأي فعالية.",
    'event_participants': "مشاركو الفعالية",
    'my_stats': "إحصائياتي",
    'total_booked': "إجمالي المحجوز",
    'total_scanned': "إجمالي الممسوح",
    'tickets_i_scanned': "تذاكر قمت بمسحها",
    'no_scans_recorded': 'لا توجد مسحات مسجلة',
    'completed_upper': 'مكتمل',
    'date_time_label': 'التاريخ والوقت',
    'venue_label': 'القاعة',
    'at': 'في',
    'jan': 'يناير', 'feb': 'فبراير', 'mar': 'مارس', 'apr': 'أبريل', 'may': 'مايو', 'jun': 'يونيو',
    'jul': 'يوليو', 'aug': 'أغسطس', 'sep': 'سبتمبر', 'oct': 'أكتوبر', 'nov': 'نوفمبر', 'dec': 'ديسمبر',
    'participating_companies': 'الشركات المشاركة',
    'booth': 'جناح',
    'apply_for_exhibition': 'طلب مشاركة في معرض',
    'exhibition_registration_closed': 'باب الاشتراك مغلق',
    'deadline_passed_msg': 'انتهى الموعد النهائي (يغلق قبل الفعالية بـ 30 يوماً)',
    'unlimited': 'مفتوح',
  };
}
