import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('ar'); 
  Locale get locale => _locale;

  static const String _prefKey = 'selected_language';

  LanguageProvider() {
    _loadSavedLanguage();
  }

  void _loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final String? languageCode = prefs.getString(_prefKey);
    if (languageCode != null) {
      _locale = Locale(languageCode);
      notifyListeners();
    }
  }

  void setLanguage(String languageCode) async {
    if (_locale.languageCode == languageCode) return;
    
    _locale = Locale(languageCode);
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, languageCode);
  }

  bool get isArabic => _locale.languageCode == 'ar';

  String translate(String key) {
    final cleanKey = key.toLowerCase().trim();
    if (isArabic) {
      return _arabicStrings[cleanKey] ?? key;
    } else {
      return _englishStrings[cleanKey] ?? key;
    }
  }

  static const Map<String, String> _englishStrings = {
    // Categories from DB (Arabic Keys -> English Values)
    'مؤتمر': 'Conference',
    'ندوة': 'Seminar',
    'ورشة عمل': 'Workshop',
    'دورة تدريبية': 'Training Course',
    'ترفيه': 'Entertainment',
    'ملتقى علمي': 'Scientific Forum',
    'رياضة': 'Sports',
    'تقنية': 'Technical',
    'اجتماعية': 'Social',
    'معرض': 'Exhibition',

    'settings': 'Settings',
    'account': 'Account',
    'notifications': 'Notifications',
    'app_preferences': 'App Preferences',
    'support': 'Support',
    'about': 'About',
    'language': 'Language',
    'change_email': 'Change Email',
    'change_password': 'Change Password',
    'push_notifications': 'Push Notifications',
    'help_center': 'Help Center',
    'contact_support': 'Contact Support',
    'version': 'Version',
    'legal_notices': 'Legal Notices',
    'logout': 'Log Out',
    'select_language': 'Select Language',
    'english': 'English',
    'arabic': 'Arabic (العربية)',
    'cancel': 'Cancel',
    'confirm_logout': 'Are you sure you want to logout?',
    'home': 'Home',
    'my_tickets': 'My Tickets',
    'profile': 'Profile',
    'search': 'Search',
    'filters': 'Filters',
    'upcoming_events': 'Upcoming Events',
    'history': 'History',
    'retry': 'Retry',
    'connection_error': 'Connection Error',
    'update': 'Update',
    'change': 'Change',
    'current_email': 'Current Email',
    'new_email': 'New Email',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'forgot_password': 'Forgot Password?',
    'verify_identity': 'Verify your identity to continue',
    'edit_profile': 'Edit Profile',
    'verified': 'Verified',
    'statistics': 'Statistics',
    'tickets_booked': 'Tickets Booked',
    'events_attended': 'Events Attended',
    'interests': 'Interests',
    'no_interests': 'No interests added yet.',
    'edit': 'Edit',
    'live_events': 'Live Events',
    'live': 'LIVE',
    'selling_fast': 'Selling Fast',
    'booking_closed': 'Booking Closed',
    'view_details': 'View Details',
    'view_tickets': 'View Tickets',
    'no_upcoming_events': 'No upcoming events',
    'no_live_events': 'No live events',
    'venue': 'Venue',
    'date': 'Date',
    'time': 'Time',
    'tickets': 'Tickets',
    'price': 'Price',
    'book_now': 'Book Now',
    'rate_review': 'Rate & Review',
    'rating': 'Rating',
    'reviews': 'Reviews',
    'description': 'Description',
    'organizer': 'Organizer',
    'all': 'All',
    'technical': 'Technical',
    'workshop': 'Workshop',
    'conference': 'Conference',
    'seminar': 'Seminar',
    'cultural': 'Cultural',
    'business': 'Business',
    'ai': 'AI',
    'networking': 'Networking',
    'fintech': 'FinTech',
    'innovation': 'Innovation',
    'sustainability': 'Sustainability',
    'entrepreneurship': 'Entrepreneurship',
    'other': 'Other',
    'confirmed': 'Confirmed',
    'used': 'Used',
    'pending': 'Pending',
    'valid': 'Valid',
    'my_events': 'My Events',
    'no_notifications': 'No notifications yet',
    'mark_all_read': 'Mark all as read',
    'apply_filters': 'Apply Filters',
    'categories': 'Categories',
    'started': 'Started',
    'open_for_booking': 'Open for Booking',
    'date_time': 'Date & Time',
    'organized_by': 'Organized by',
    'about_event': 'About This Event',
    'event_agenda': 'Event Agenda',
    'event_sponsors': 'Event Sponsors',
    'leave_review': 'Leave a Review',
    'see_all': 'See All',
    'confirm_booking': 'Confirm Booking',
    'booking_confirm_msg': 'Are you sure you want to book a ticket for',
    'ticket_booked_success': 'Ticket Booked Successfully!',
    'rating_submitted': 'Rating submitted!',
    'write_review': 'Write a review (optional)...',
    'submit_rating': 'Submit Rating',
    'capacity_bookings': 'Capacity & Bookings',
    'sold_out': 'Sold Out!',
    'booked': 'Booked',
    'no_history': 'No history yet',
    'book_ticket_hint': 'Book a ticket from Explore tab',
    'attended': 'Attended',
    'active': 'Active',
    'expired': 'Expired',
    'confirm': 'Confirm',
    'booking_closed_msg': 'Booking Closed',
    'already_booked': 'Already Booked',
    'notification_hint': "You'll get alerts for events, tickets & more",
    'agenda': 'Agenda Item',
    'access_ticket': 'Access Ticket',
    'scan_entrance': 'Scan at the entrance',
    'ticket_used': 'TICKET USED',
    'valid_ticket': 'VALID TICKET',
    'qr_safe_msg': 'Keep this QR code safe. You will need it to enter the event.',
    'ticket_label': 'TICKET',
    'passwords_not_match': 'Passwords do not match',
    'password_updated': 'Password updated successfully!',
    'email_updated': 'Email updated successfully!',
    'select_interests': 'Select Interests',
    'done': 'Done',
    'full_name': 'Full Name',
    'your_full_name': 'Your full name',
    'email_address': 'Email Address',
    'email_hint': 'you@example.com',
    'new_password_optional': 'New Password (optional)',
    'pass_hint': 'Leave empty to keep current',
    'profile_updated': 'Profile updated successfully!',
    'rate_event': 'Rate Event',
    'select_star_rating': 'Please select a star rating first.',
    'rating_success': 'Rating submitted successfully!',
    'based_on': 'Based on',
    'no_reviews_msg': 'No reviews yet for this event.',
    'rating_locked_msg': 'You must attend and scan your ticket to leave a review.',
    'share_event': 'Share Event',
    'share_msg': 'Check out this event on EventHub!',
  };

  static const Map<String, String> _arabicStrings = {
    // Categories from DB (Arabic Keys -> Arabic Values)
    'مؤتمر': 'مؤتمر',
    'ندوة': 'ندوة',
    'ورشة عمل': 'ورشة عمل',
    'دورة تدريبية': 'دورة تدريبية',
    'ترفيه': 'ترفيه',
    'ملتقى علمي': 'ملتقى علمي',
    'رياضة': 'رياضة',
    'تقنية': 'تقنية',
    'اجتماعية': 'اجتماعية',
    'معرض': 'معرض',

    'settings': 'الإعدادات',
    'account': 'الحساب',
    'notifications': 'الإشعارات',
    'app_preferences': 'تفضيلات التطبيق',
    'support': 'الدعم',
    'about': 'حول التطبيق',
    'language': 'اللغة',
    'change_email': 'تغيير البريد الإلكتروني',
    'change_password': 'تغيير كلمة المرور',
    'push_notifications': 'تنبيهات الهاتف',
    'help_center': 'مركز المساعدة',
    'contact_support': 'الاتصال بالدعم',
    'version': 'الإصدار',
    'legal_notices': 'ملاحظات قانونية',
    'logout': 'تسجيل الخروج',
    'select_language': 'اختر اللغة',
    'english': 'الإنجليزية (English)',
    'arabic': 'العربية',
    'cancel': 'إلغاء',
    'confirm_logout': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    'home': 'الرئيسية',
    'my_tickets': 'تذاكري',
    'profile': 'الملف الشخصي',
    'search': 'بحث',
    'filters': 'تصفية',
    'upcoming_events': 'الفعاليات القادمة',
    'history': 'السجل',
    'retry': 'إعادة المحاولة',
    'connection_error': 'خطأ في الاتصال',
    'update': 'تحديث',
    'change': 'تغيير',
    'current_email': 'البريد الإلكتروني الحالي',
    'new_email': 'البريد الإلكتروني الجديد',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'forgot_password': 'نسيت كلمة المرور؟',
    'verify_identity': 'يرجى تأكيد هويتك للمتابعة',
    'edit_profile': 'تعديل الملف الشخصي',
    'verified': 'موثق',
    'statistics': 'الإحصائيات',
    'tickets_booked': 'التذاكر المحجوزة',
    'events_attended': 'الفعاليات التي حضرتها',
    'interests': 'الاهتمامات',
    'no_interests': 'لا توجد اهتمامات مضافة بعد.',
    'edit': 'تعديل',
    'live_events': 'فعاليات مباشرة',
    'live': 'مباشر',
    'selling_fast': 'تنفد بسرعة',
    'booking_closed': 'الحجز مغلق',
    'view_details': 'عرض التفاصيل',
    'view_tickets': 'عرض التذاكر',
    'no_upcoming_events': 'لا توجد فعاليات قادمة',
    'no_live_events': 'لا توجد فعاليات مباشرة حالياً',
    'venue': 'القاعة',
    'date': 'التاريخ',
    'time': 'الوقت',
    'tickets': 'التذاكر',
    'price': 'السعر',
    'book_now': 'احجز الآن',
    'rate_review': 'التقييم والمراجعة',
    'rating': 'التقييم',
    'reviews': 'المراجعات',
    'description': 'الوصف',
    'organizer': 'المنظم',
    'all': 'الكل',
    'technical': 'تقني',
    'workshop': 'ورشة عمل',
    'conference': 'مؤتمر',
    'seminar': 'ندوة',
    'cultural': 'ثقافي',
    'business': 'الأعمال',
    'ai': 'الذكاء الاصطناعي',
    'networking': 'التواصل',
    'fintech': 'التقنية المالية',
    'innovation': 'الابتكار',
    'sustainability': 'الاستدامة',
    'entrepreneurship': 'ريادة الأعمال',
    'other': 'أخرى',
    'confirmed': 'مؤكد',
    'used': 'مستخدم',
    'pending': 'قيد الانتظار',
    'valid': 'صالح',
    'my_events': 'فعالياتي',
    'no_notifications': 'لا توجد إشعارات بعد',
    'mark_all_read': 'تحديد الكل كمقروء',
    'apply_filters': 'تطبيق الفلتر',
    'categories': 'التصنيفات',
    'started': 'بدأت',
    'open_for_booking': 'مفتوح للحجز',
    'date_time': 'التاريخ والوقت',
    'organized_by': 'بواسطة',
    'about_event': 'حول الفعالية',
    'event_agenda': 'جدول الفعالية',
    'event_sponsors': 'رعاة الفعالية',
    'leave_review': 'أضف مراجعة',
    'see_all': 'مشاهدة الكل',
    'confirm_booking': 'تأكيد الحجز',
    'booking_confirm_msg': 'هل أنت متأكد أنك تريد حجز تذكرة لـ',
    'ticket_booked_success': 'تم حجز التذكرة بنجاح!',
    'rating_submitted': 'تم إرسال التقييم!',
    'write_review': 'اكتب مراجعة (اختياري)...',
    'submit_rating': 'إرسال التقييم',
    'capacity_bookings': 'السعة والحجوزات',
    'sold_out': 'نفدت التذاكر!',
    'booked': 'محجوز',
    'no_history': 'لا يوجد سجل بعد',
    'book_ticket_hint': 'احجز تذكرة من قسم الاستكشاف',
    'attended': 'حضر',
    'active': 'نشط',
    'expired': 'منتهي',
    'confirm': 'تأكيد',
    'booking_closed_msg': 'الحجز مغلق',
    'already_booked': 'تم الحجز مسبقاً',
    'notification_hint': 'ستصلك تنبيهات حول الفعاليات والتذاكر والمزيد',
    'agenda': 'فقرة في الجدول',
    'access_ticket': 'الدخول للتذكرة',
    'scan_entrance': 'امسح الرمز عند المدخل',
    'ticket_used': 'تذكرة مستخدمة',
    'valid_ticket': 'تذكرة صالحة',
    'qr_safe_msg': 'حافظ على هذا الرمز آمناً. ستحتاج إليه لدخول الفعالية.',
    'ticket_label': 'تذكرة',
    'passwords_not_match': 'كلمات المرور غير متطابقة',
    'password_updated': 'تم تحديث كلمة المرور بنجاح!',
    'email_updated': 'تم تحديث البريد الإلكتروني بنجاح!',
    'select_interests': 'اختر اهتماماتك',
    'done': 'تم',
    'full_name': 'الاسم بالكامل',
    'your_full_name': 'اسمك بالكامل',
    'email_address': 'البريد الإلكتروني',
    'email_hint': 'you@example.com',
    'new_password_optional': 'كلمة مرور جديدة (اختياري)',
    'pass_hint': 'اتركه فارغاً للاحتفاظ بالحالية',
    'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
    'rate_event': 'تقييم الفعالية',
    'select_star_rating': 'يرجى اختيار عدد النجوم أولاً.',
    'rating_success': 'تم إرسال التقييم والمراجعة بنجاح!',
    'based_on': 'بناءً على',
    'no_reviews_msg': 'لا توجد مراجعات لهذه الفعالية بعد.',
    'rating_locked_msg': 'يجب حضور الفعالية ومسح التذكرة لتتمكن من التقييم والتعليق.',
    'share_event': 'مشاركة الفعالية',
    'share_msg': 'شاهد هذه الفعالية على EventHub!',
  };
}
